In [1]:
# d6617
# The code to run the system. Cause jupyter is just..... better

from environment import Simulator
from lowest_alg import Lowest
import numpy as np

import logging

logger = logging.getLogger('jerry')
logger.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
ch.setFormatter(formatter)
logger.addHandler(ch)


logger.debug('Hi')
# Save logs to file
# fh = logging.FileHandler('jerry.log')
#fh.setLevel(logging.DEBUG)



lowest = Lowest()

players = 4
observations = 'limited'  # limited or expanded mode of observations
algs = [lowest, lowest, lowest, lowest]

sim = Simulator(players=4, observations=observations)
sim.load_algorithms(algs)


2020-05-05 22:09:06,869 - jerry - DEBUG - Hi
2020-05-05 22:09:06,874 - jerry.environment - INFO - Hearts engine initlised
2020-05-05 22:09:06,878 - jerry.environment - INFO - Player 0's hand
[[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2020-05-05 22:09:06,888 - jerry.environment - INFO - Player 1's hand
[[0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]]
2020-05-05 22:09:06,893 - jerry.environment - INFO - Player 2's hand
[[0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0.]]
2020-05-05 22:09:06,900 - jerry.environment - INFO - Player 3's hand
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 

In [2]:
starting_player = 0  # make this ace of clubs eventually
done = False
i = 1

while i < 14:
    logger.info('\n#--- ROUND ' + str(i))
    #sim.print_cards()
    # For each round:
    # For each player in round
    # Choose an action depending on the state
    # Do the action
    # Compute the reward
    # (Q table modification if applicable)
    # Change new state, to current state
    # Compute points
    logger.info('$--- Player Turn ' + str(starting_player))
    a = sim.init_state(starting_player)
    sim.step(starting_player, a)
    move = 1
    
    while move < players:
        # So only a certain number of moves
        
        turn = starting_player + move
        if turn > 3:
            turn -= 4  # Loop back around
        logger.info('$--- Player Turn' + str(turn))
        
        s = sim.gen_state(turn)
        logger.info('State of ' + str(s))
        
        a = sim.choose(turn, s)  # Make a decision
        sim.step(turn, a)  # play that decision

        move += 1
    #sim.find_winner()
    i += 1
sim.print_cards()
logger.info('Cards left' + str(np.sum(sim.current_hands)))

2020-05-05 22:09:09,468 - jerry - INFO - 
#--- ROUND 1
2020-05-05 22:09:09,470 - jerry - INFO - $--- Player Turn 0
2020-05-05 22:09:09,473 - jerry.lowest_alg - INFO - Cards:
[[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2020-05-05 22:09:09,476 - jerry.lowest_alg - DEBUG - 0 ==> 0
2020-05-05 22:09:09,479 - jerry.lowest_alg - DEBUG - 1 ==> 0
2020-05-05 22:09:09,481 - jerry.lowest_alg - INFO - (Best card) Choose(0, 1)
2020-05-05 22:09:09,483 - jerry.environment - INFO - $--- CARDS Played[(0, 1)]
2020-05-05 22:09:09,485 - jerry - INFO - $--- Player Turn1
2020-05-05 22:09:09,487 - jerry.environment - DEBUG - Obseration shape(2, 4, 14)
2020-05-05 22:09:09,493 - jerry - INFO - State of [[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

Cards:
 [[0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0.]]
Choose (1, 1)


(1, 1)